config/routes.rb
Rails.application.routes.draw do
 
  get 'chats/show'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'homes#index'
  resources :reactions, only: [:create]
  resources :matching, only: [:index]
  get 'chat/:id', to: 'chats#show', as: 'chat'
  resources :chats, only: [:create]
  resources :chat_rooms, only: [:create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/models/chat_room.rb
class ChatRoom < ApplicationRecord
    has_many :chat_room_users
    has_many :users, through: :chat_room_users
end

app/models/chat_room_user.rb
class ChatRoomUser < ApplicationRecord
    belongs_to :chat_room
    belongs_to :user
end

app/models/reaction.rb
class Reaction < ApplicationRecord
    belongs_to :to_user, class_name: "User"
    belongs_to :from_user, class_name: "User"

    enum status: { like: 0, dislike: 1 }
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :chats
    has_many :user_rooms 
end

app/models/user.rb
class User < ApplicationRecord

  has_many :reactions
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  has_many :chat_room_users
  has_many :chat_rooms, through: :chat_room_users

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
    belongs_to :user
    belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_rooms_controller.rb
class ChatRoomsController < ApplicationController
    before_action :authenticate_user!
    def create
        current_user_chat_rooms = ChatRoomUser.where(user_id: current_user.id).map(&:chat_room)
        chat_room = ChatRoomUser.where(chat_room: current_user_chat_rooms, user_id: params[:user_id]).map(&:chat_room).first
        if chat_room.blank?
          chat_room = ChatRoom.create
          ChatRoomUser.create(chat_room: chat_room, user_id: current_user.id)
          ChatRoomUser.create(chat_room: chat_room, user_id: params[:user_id])
        end
        redirect_to action: :show, id: chat_room.id
    end
  
    def show
    end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)
  
    if user_rooms.nil?
     @room = Room.new
     @room.save
     UserRoom.create(user_id: @user.id, room_id: @room.id)
     UserRoom.create(user_id: current_user.id, room_id: @room.id)
    else
     @room = user_rooms.room
    end
  
    @chats = @room.chats
    @chat = Chat.new(room_id: @room.id)
   end
  
   def create
    @chat = current_user.chats.new(chat_params)
    @chat.save
   end
  
   private
  
   def chat_params
    params.require(:chat).permit(:message, :room_id)
   end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/matching_controller.rb
class MatchingController < ApplicationController
    before_action :authenticate_user!

    def index
        got_reaction_user_ids = Reaction.where(to_user_id: current_user.id, status: 'like').pluck(:from_user_id)
        @match_users = Reaction.where(to_user_id: got_reaction_user_ids, from_user_id: current_user.id, status: 'like').map(&:to_user)
        @user = User.find(current_user.id)    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_rooms_helper.rb
module ChatRoomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/matching_helper.rb
module MatchingHelper
end

app/views/chat_rooms/show.html.erb
<p>チャットルームページ</p>

app/views/chats/create.js.erb
/*.messageを部分更新。appendメソッドで要素を追加 */
$('.message').append("<p style='text-align: left;'><%= @chat.message %></p>");

/*チャット投稿後、フォームの値に前回の投稿内容が残らないようにする */
$('input[type=text]').val("")

app/views/chats/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-xs-6">
            <h2>CHAT WITH <%= @user.name %></h2>

            <table class="message table">
              <thead>
                <tr>
                  <th style="text-align: left; font-size: 20px;"><%= current_user.name %></th>
                  <th style="text-align: right; font-size: 20px;"><%= @user.name %></th>
                </tr>
              </thead>
              <% @chats.each do |chat| %>
                <% if chat.user_id == current_user.id %>
                <tbody>
                  <tr>
                    <th>
                      <p style="text-align: left;"><%= chat.message %></p>
                    </th>
                    <th></th>
                  </tr>
                <% else %>
                  <tr>
                    <th></th>
                    <th>
                      <p style="text-align: right;"><%= chat.message %></p>
                    </th>
                  </tr>
                </tbody>
                <% end %>
              <% end %>
            </table>

            <%= form_with model: @chat, remote: true do |f| %>
              <%= f.text_field :message %>
              <%= f.hidden_field :room_id %>
              <%= f.submit "SEND", class:"btn btn-sm btn-success chat-btn" %>
            <% end %>
        </div>
    </div>
</div>

app/views/homes/index.html.erb
<h1>Homes#index</h1>
<p>Find me in app/views/homes/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
    <div class="header__bar row">
      <h1 class="grid-6">TOP画面（仮）</h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: 'post' %>
          <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
        </div>
      <% end %>
    </div>
  </header>
    <%= yield %>
  </body>
</html>

app/views/matching/index.html.erb
<div class="matching__list">
  <% unless @match_users.empty? %>
    <% @match_users.each do |user| %>

      <%# この行を追加 %>
      <%= link_to chat_rooms_path(params: { user_id: user.id }), method: :post do %>

        <div class="matching__person">

          <div class="matching__person-name">
            <%= user.name %>
          </div>

        </div>
      
      <%# この行を追加 %>
      <% end %>

    <% end %>
  <% end %>
</div>